import { useEffect, useMemo, useState } from 'react';
import { NavLink, Route, Routes } from 'react-router-dom';
import { BarChart3, BrainCircuit, ChevronRight, FileCheck2, FileUp, FolderTree, LayoutDashboard, Menu, Search, Settings, Sparkles, Tags, X } from 'lucide-react';
import { api, type Dashboard, type Story } from './api';

const nav = [
  ['Dashboard', '/', LayoutDashboard], ['Classificar histórias', '/classify', Sparkles], ['Fila de revisão', '/review', FileCheck2],
  ['Taxonomia', '/taxonomy', FolderTree], ['Execuções', '/runs', BrainCircuit], ['Configurações', '/settings', Settings]
] as const;

function Layout() {
  const [open, setOpen] = useState(false);
  return <div className="shell">
    <aside className={open ? 'sidebar open' : 'sidebar'}>
      <div className="brand"><span className="brand-icon"><BrainCircuit size={19}/></span><div><strong>US-Agent</strong><small>AI Classification</small></div></div>
      <nav>{nav.map(([label, path, Icon]) => <NavLink key={path} to={path} end={path === '/'} onClick={() => setOpen(false)}><Icon size={17}/><span>{label}</span></NavLink>)}</nav>
      <div className="sidebar-foot"><div className="avatar">CE</div><div><b>Carlos Eduardo</b><small>Administrador</small></div></div>
    </aside>
    <main><header><button className="icon-button mobile" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button><div className="global-search"><Search size={16}/><input placeholder="Buscar histórias, módulos ou execuções..."/></div><span className="environment">Ambiente local</span><div className="avatar">CE</div></header><Routes>
      <Route path="/" element={<DashboardPage/>}/><Route path="/classify" element={<ClassifyPage/>}/><Route path="/review" element={<ReviewPage/>}/><Route path="/taxonomy" element={<TaxonomyPage/>}/><Route path="/runs" element={<StoriesPage/>}/><Route path="*" element={<Placeholder/>}/>
    </Routes></main>
  </div>;
}

function PageTitle({ eyebrow, title, children }: { eyebrow?: string; title: string; children?: string }) {
  return <div className="page-title"><div>{eyebrow && <span>{eyebrow}</span>}<h1>{title}</h1>{children && <p>{children}</p>}</div></div>;
}
function State({ loading, error }: { loading: boolean; error: string }) { if (loading) return <div className="state">Carregando dados…</div>; if (error) return <div className="state error">{error}</div>; return null; }

function DashboardPage() {
  const [data, setData] = useState<Dashboard>(); const [stories, setStories] = useState<Story[]>([]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.dashboard(), api.stories()]).then(([d,s]) => { setData(d); setStories(s.slice(0,6)); }).catch(e => setError(e.message)); }, []);
  return <section className="page"><PageTitle eyebrow="VISÃO GERAL" title="Bom dia, Carlos">Acompanhe a qualidade e o ritmo das classificações.</PageTitle><State loading={!data && !error} error={error}/>{data && <>
    <div className="metrics"><Metric label="Histórias classificadas" value={String(data.total)} trend="base atual"/><Metric label="Confiança média" value={`${Math.round(data.confidence*100)}%`} trend="modelos combinados" tone="green"/><Metric label="Aguardando revisão" value={String(data.pending)} trend="requer atenção" tone="orange"/><Metric label="Aceitas automaticamente" value={String(data.accepted)} trend="baixo risco" tone="blue"/></div>
    <div className="dashboard-grid"><div className="card span2"><CardHead title="Classificações recentes" action="Ver todas"/><StoryTable stories={stories}/></div><div className="card"><CardHead title="Distribuição por módulo"/>{data.modules.slice(0,5).map((m,i) => <div className="bar-row" key={m.name}><div><span>{m.name}</span><b>{m.count}</b></div><div className="bar"><i style={{width:`${Math.max(8,m.count/(data.modules[0]?.count||1)*100)}%`, background: ['#2563eb','#7c3aed','#06b6d4','#f59e0b','#64748b'][i]}}/></div></div>)}</div></div>
  </>}</section>;
}
function Metric({ label, value, trend, tone='purple' }: {label:string;value:string;trend:string;tone?:string}) { return <div className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{trend}</small></div>; }
function CardHead({title,action}:{title:string;action?:string}) { return <div className="card-head"><h2>{title}</h2>{action&&<button className="text-button">{action} <ChevronRight size={14}/></button>}</div>; }
function Status({ value }: { value: string }) { const pending = ['pending_review','taxonomy_gap','needs_rewrite'].includes(value); return <span className={`badge ${pending?'warning':'success'}`}>{pending?'Revisar':'Concluída'}</span>; }
function StoryTable({stories}:{stories:Story[]}) { return <div className="table-wrap"><table><thead><tr><th>História</th><th>Classificação</th><th>Confiança</th><th>Status</th></tr></thead><tbody>{stories.map(s=><tr key={s.id}><td><b>{s.text}</b><small>{s.project}</small></td><td><span className="tag">{s.module}</span><small>{s.operation}</small></td><td><b>{Math.round(s.confidence*100)}%</b></td><td><Status value={s.status}/></td></tr>)}</tbody></table>{!stories.length&&<div className="empty">Nenhuma história encontrada.</div>}</div>; }

function ClassifyPage() {
  const [text,setText]=useState(''); const [project,setProject]=useState('Meu projeto'); const [running,setRunning]=useState(false); const [results,setResults]=useState<any[]>([]); const [error,setError]=useState('');
  const stories=useMemo(()=>text.split(/\n|;/).map(x=>x.trim()).filter(Boolean),[text]);
  async function run(){ setError(''); setRunning(true); try{setResults((await api.classify(stories,project)).results)}catch(e){setError((e as Error).message)}finally{setRunning(false)} }
  async function fileChanged(file?:File){if(!file)return;try{const r=await api.importFile(file);setText(r.stories.join('\n'))}catch(e){setError((e as Error).message)}}
  return <section className="page"><PageTitle eyebrow="CLASSIFICAÇÃO" title="Classificar histórias">Cole requisitos ou importe um arquivo para obter uma pré-classificação instantânea.</PageTitle><div className="classify-grid"><div className="card editor-card"><div className="form-row"><label>Projeto<input value={project} onChange={e=>setProject(e.target.value)}/></label><label className="file-button"><FileUp size={16}/> Importar TXT/CSV<input type="file" accept=".txt,.csv" onChange={e=>fileChanged(e.target.files?.[0])}/></label></div><label>Histórias de usuário<textarea value={text} onChange={e=>setText(e.target.value)} placeholder={'Uma história por linha. Exemplo:\nComo usuário, quero entrar com minha conta Google para acessar rapidamente.'}/></label><div className="editor-foot"><span>{stories.length} história(s)</span><button className="primary" disabled={!stories.length||running} onClick={run}><Sparkles size={17}/>{running?'Classificando…':'Iniciar classificação'}</button></div>{error&&<p className="inline-error">{error}</p>}</div><div className="card config"><CardHead title="Configuração da execução"/><label>Modo<select><option>Pré-classificação rápida</option><option>Comitê de modelos</option></select></label><div className="model active"><BrainCircuit size={18}/><div><b>Motor híbrido</b><small>Regras locais + LLM integrado</small></div><span>Ativo</span></div><div className="hint">A prévia não altera os resultados históricos. A execução com modelos será conectada ao orquestrador existente.</div></div></div>{results.length>0&&<div className="card results"><CardHead title="Resultado da pré-classificação"/><div className="result-grid">{results.map(r=><article key={r.id}><p>{r.text}</p><div><span className="tag">{r.module}</span><b>{r.operation}</b></div><footer><span>{Math.round(r.confidence*100)}% de confiança</span>{r.needsReview&&<span className="badge warning">Revisar</span>}</footer></article>)}</div></div>}</section>;
}

function ReviewPage(){const [stories,setStories]=useState<Story[]>([]);const [selected,setSelected]=useState<Story>();useEffect(()=>{api.stories().then(s=>{const p=s.filter(x=>['pending_review','taxonomy_gap','needs_rewrite'].includes(x.status));setStories(p);setSelected(p[0])})},[]);return <section className="page"><PageTitle eyebrow="HUMAN IN THE LOOP" title="Fila de revisão">Valide os casos com maior incerteza antes de consolidar a base.</PageTitle><div className="review-grid"><div className="card queue"><CardHead title={`Pendentes (${stories.length})`}/>{stories.map(s=><button className={selected?.id===s.id?'queue-item selected':'queue-item'} onClick={()=>setSelected(s)} key={s.id}><span className="risk-dot"/><div><b>{s.text}</b><small>{s.module} · {Math.round(s.confidence*100)}% confiança</small></div><ChevronRight size={16}/></button>)}{!stories.length&&<div className="empty">A fila está vazia.</div>}</div><div className="card review-panel">{selected?<><span className="badge warning">Revisão necessária</span><h2>{selected.text}</h2><div className="score-row"><div><small>Confiança</small><strong>{Math.round(selected.confidence*100)}%</strong></div><div><small>Consenso</small><strong>{Math.round(selected.consensus*100)}%</strong></div><div><small>Incerteza</small><strong>{Math.round(selected.uncertainty*100)}%</strong></div></div><label>Módulo<input defaultValue={selected.module}/></label><label>Operação<input defaultValue={selected.operation}/></label><label>Justificativa<textarea className="small-area" placeholder="Registre o motivo da decisão…"/></label><div className="actions"><button>Marcar lacuna</button><button className="primary">Aprovar classificação</button></div></>:<div className="empty large">Selecione uma história para revisar.</div>}</div></div></section>}

function TaxonomyPage(){const [data,setData]=useState<{version:string;modules:Record<string,string[]>}>();const [selected,setSelected]=useState<string>();useEffect(()=>{api.taxonomy().then(d=>{setData(d);setSelected(Object.keys(d.modules)[0])})},[]);return <section className="page"><PageTitle eyebrow="GOVERNANÇA" title="Gerenciar taxonomia">Explore os módulos e operações usados pelo comitê de classificação.</PageTitle>{data&&<div className="taxonomy-grid"><div className="card tree"><div className="version"><Tags size={18}/><div><b>Taxonomia WIS</b><small>Versão {data.version}</small></div></div>{Object.entries(data.modules).map(([name,ops])=><button className={selected===name?'selected':''} onClick={()=>setSelected(name)} key={name}><FolderTree size={17}/><span>{name}</span><small>{ops.length}</small></button>)}</div><div className="card node"><span className="eyebrow">MÓDULO</span><h1>{selected}</h1><p>Operações disponíveis para classificação neste módulo.</p><div className="operations">{selected&&data.modules[selected].map((op,i)=><div key={op}><span>{String(i+1).padStart(2,'0')}</span><b>{op}</b><span className="badge success">Ativa</span></div>)}</div></div></div>}</section>}
function StoriesPage(){const [s,setS]=useState<Story[]>([]);useEffect(()=>{api.stories().then(setS)},[]);return <section className="page"><PageTitle eyebrow="HISTÓRICO" title="Execuções e resultados">Consulte as classificações processadas pelo agente.</PageTitle><div className="card"><StoryTable stories={s}/></div></section>}
function Placeholder(){return <section className="page"><PageTitle title="Configurações">Esta área será habilitada na próxima etapa de integração.</PageTitle></section>}
export default Layout;
